apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
        - name: django-todo
          image: yash5090/django-todo:latest # Replace with the actual image tag
          ports:
            - containerPort: 8000 # Replace with the port your Tetris game listens on
